// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelBookingWeb.Data;

#nullable disable

namespace TravelBookingWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260502223159_FinalCleanSetup")]
    partial class FinalCleanSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelBookingWeb.Models.Activitate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DestinatieId")
                        .HasColumnType("int");

                    b.Property<string>("Durata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Imagine");

                    b.Property<string>("Nume_Activitate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nume_Activitate");

                    b.Property<decimal>("Pret_pe_persoana")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Pret_pe_persoana");

                    b.HasKey("Id");

                    b.HasIndex("DestinatieId");

                    b.ToTable("Activitati", (string)null);
                });

            modelBuilder.Entity("TravelBookingWeb.Models.Camera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacitate")
                        .HasColumnType("int");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<decimal>("Pret_pe_noapte")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tip_Camera")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Camere");
                });

            modelBuilder.Entity("TravelBookingWeb.Models.Destinatie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Oras")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tara")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Destinatii");
                });

            modelBuilder.Entity("TravelBookingWeb.Models.Facilitate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nume_Facilitate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Facilitati");
                });

            modelBuilder.Entity("TravelBookingWeb.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AreAerConditionat")
                        .HasColumnType("bit");

                    b.Property<bool>("AreFitness")
                        .HasColumnType("bit");

                    b.Property<bool>("AreMicDejun")
                        .HasColumnType("bit");

                    b.Property<bool>("AreParcare")
                        .HasColumnType("bit");

                    b.Property<bool>("ArePiscina")
                        .HasColumnType("bit");

                    b.Property<bool>("AreSpa")
                        .HasColumnType("bit");

                    b.Property<bool>("AreWiFi")
                        .HasColumnType("bit");

                    b.Property<string>("Descriere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DestinatieId")
                        .HasColumnType("int");

                    b.Property<int?>("FacilitateId")
                        .HasColumnType("int");

                    b.Property<string>("ImaginiGalerie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("PermiteAnimale")
                        .HasColumnType("bit");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PretBaza")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,1)");

                    b.Property<int>("Stele")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinatieId");

                    b.HasIndex("FacilitateId");

                    b.ToTable("Hoteluri");
                });

            modelBuilder.Entity("TravelBookingWeb.Models.Inchirieri_Masini", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DestinatieId")
                        .HasColumnType("int");

                    b.Property<string>("Model_Masina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pret_pe_zi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tip_Masina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transmisie")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DestinatieId");

                    b.ToTable("Inchirieri_Masini");
                });

            modelBuilder.Entity("TravelBookingWeb.Models.Recenzie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data_postarii")
                        .HasColumnType("datetime2");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("Pareri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Scor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Recenzii");
                });

            modelBuilder.Entity("TravelBookingWeb.Models.Rezervare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataInceput")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataRezervare")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataSfarsit")
                        .HasColumnType("datetime2");

                    b.Property<string>("DetaliiServiciu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Facilitati")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetodaPlata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PretTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ServiciuId")
                        .HasColumnType("int");

                    b.Property<string>("StatusPlata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipServiciu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Rezervari");
                });

            modelBuilder.Entity("TravelBookingWeb.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parola")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TravelBookingWeb.Models.Zbor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanieAeriana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Companie_Aeriana");

                    b.Property<int?>("DestinatieId")
                        .HasColumnType("int");

                    b.Property<string>("Durata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Escale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DestinatieId");

                    b.ToTable("Zboruri");
                });

            modelBuilder.Entity("TravelBookingWeb.Models.Activitate", b =>
                {
                    b.HasOne("TravelBookingWeb.Models.Destinatie", "Destinatie")
                        .WithMany("Activitati")
                        .HasForeignKey("DestinatieId");

                    b.Navigation("Destinatie");
                });

            modelBuilder.Entity("TravelBookingWeb.Models.Camera", b =>
                {
                    b.HasOne("TravelBookingWeb.Models.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("TravelBookingWeb.Models.Hotel", b =>
                {
                    b.HasOne("TravelBookingWeb.Models.Destinatie", "Destinatie")
                        .WithMany("Hoteluri")
                        .HasForeignKey("DestinatieId");

                    b.HasOne("TravelBookingWeb.Models.Facilitate", null)
                        .WithMany("Hoteluri")
                        .HasForeignKey("FacilitateId");

                    b.Navigation("Destinatie");
                });

            modelBuilder.Entity("TravelBookingWeb.Models.Inchirieri_Masini", b =>
                {
                    b.HasOne("TravelBookingWeb.Models.Destinatie", "Destinatie")
                        .WithMany("Masini")
                        .HasForeignKey("DestinatieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destinatie");
                });

            modelBuilder.Entity("TravelBookingWeb.Models.Recenzie", b =>
                {
                    b.HasOne("TravelBookingWeb.Models.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("TravelBookingWeb.Models.Rezervare", b =>
                {
                    b.HasOne("TravelBookingWeb.Models.User", "User")
                        .WithMany("Rezervari")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelBookingWeb.Models.Zbor", b =>
                {
                    b.HasOne("TravelBookingWeb.Models.Destinatie", "Destinatie")
                        .WithMany("Zboruri")
                        .HasForeignKey("DestinatieId");

                    b.Navigation("Destinatie");
                });

            modelBuilder.Entity("TravelBookingWeb.Models.Destinatie", b =>
                {
                    b.Navigation("Activitati");

                    b.Navigation("Hoteluri");

                    b.Navigation("Masini");

                    b.Navigation("Zboruri");
                });

            modelBuilder.Entity("TravelBookingWeb.Models.Facilitate", b =>
                {
                    b.Navigation("Hoteluri");
                });

            modelBuilder.Entity("TravelBookingWeb.Models.User", b =>
                {
                    b.Navigation("Rezervari");
                });
#pragma warning restore 612, 618
        }
    }
}
